/// <reference path="../../globals.d.ts" />
// maps equipped card IDs to their Idleon Calculator display labels.
const cardEquipMap: StringMap = {
    "B": "None",
    "mushG": "Green Mushroom (+ Base HP)",
    "mushR": "Red Mushroom (+ Base LUK)",
    "frogG": "Frog (+ Base MP)",
    "beanG": "Bored Bean (+ Base Damage)",
    "slimeG": "Slime (+ Base WIS)",
    "snakeG": "Baby Boa (+ Move Spd)",
    "carrotO": "Carrotman (+ Base AGI)",
    "goblinG": "Glublin (+% Total HP)",
    "plank": "Wode Board (+ Base STR)",
    "frogBIG": "Gigafrog (+% Card Drop Chance)",
    "poopSmall": "Poop (+% Crystal Mob Spawn Chance)",
    "ratB": "Rat (+% Critical Chance)",
    "branch": "Walking Stick (+ Base WIS)",
    "acorn": "Nutto (+% Money from Monsters)",
    "Crystal0": "Crystal Carrot (+% Total Drop Rate)",
    "mushW": "Wood Mushroom (+% Total Accuracy)",
    "jarSand": "Sandy Pot (+% EXP Conversion from Talent)",
    "mimicA": "Mimic (+% Total Drop Rate)",
    "crabcake": "Crabcake (+% To not consume Food)",
    "coconut": "Mafioso (+ Base AGI)",
    "sandcastle": "Sand Castle (+% Total Accuracy)",
    "pincermin": "Pincermin (+ Weapon Power)",
    "potato": "Mashed Potato (+% Critical Damage)",
    "steak": "Tyson (+ Base STR)",
    "moonman": "Moonmoon (+% Monster EXP While Active)",
    "sandgiant": "Sand Giant (+% Minimum Damage)",
    "snailZ": "Snelbie (+% Card Drop Chance)",
    "shovelR": "Dig Doug (+ Base LUK)",
    "Crystal1": "Crystal Crabal (+% EXP from monsters)",
    "Bandit_Bob": "Bandit Bob (+% Money from Monsters)",
    "Blank": "Green Mushroom (+% Base HP)",
    "Copper": "Copper Ore (+ Base accuracy)",
    "Iron": "Iron Ore (+% Total Mining Efficiency)",
    "Gold": "Gold Ore (+% Mining EXP)",
    "ForgeA": "Fire Forge (+% Smithing EXP (Passive))",
    "OakTree": "Oak Logs (+ Base Defence)",
    "BirchTree": "Bleach Logs (+% Total Choppin Efficiency)",
    "JungleTree": "Jungle Logs (+% Choppin EXP)",
    "ForestTree": "Forest Fibres (+% EXP Conversion from Talent)",
    "Fish1": "Goldfish (+% Total MP)",
    "Fish2": "Hermit Can (+% Total Fishing Efficiency)",
    "Fish3": "Jellyfish (+% Fishing EXP)",
    "Bug1": "Fly (+% Monster EXP While Active)",
    "Bug2": "Butterfly (+% Total Catching Efficiency)",
    "Plat": "Platinum Ore (+% Mining Away Gains)",
    "Dementia": "Dementia Ore (+% Mining Speed)",
    "Void": "Void Ore (+% Total Mining Efficiency)",
    "Lustre": "Lustre Ore (+% Mining Speed)",
    "ForgeB": "Cinder Forge (+% Smithing EXP (Passive))",
    "PalmTree": "Tropilogs (+% Choppin Away Gains)",
    "ToiletTree": "Potty Rolls (+% Choppin Speed)",
    "StumpTree": "Veiny Logs (+% Total Accuracy)",
    "SaharanFoal": "Tundra Logs (+% Choppin Away Gains)",
    "Tree7": "Wispy Lumber (+% Choppin Speed)",
    "AlienTree": "Alien Hive Chunk (+% Total Choppin Efficiency)",
    "Tree8": "Cubed Logs (+% Choppin Speed)",
    "Fish4": "Bloach (+% Fishing Away Gains)",
    "Fish5": "Skelefish (+% Total Fishing Efficiency)",
    "Fish6": "Sand Shark (+% Fishing Speed)",
    "Fish7": "Manta Ray (+% Fishing EXP)",
    "Fish8": "Kraken (+% Fishing Away Gains)",
    "Bug3": "Sentient Cereal (+% Catching EXP)",
    "Bug4": "Fruitfly (+% Catching Away Gains)",
    "Bug5": "Mosquisnow (+% Total Catching Efficiency)",
    "Bug6": "Flycicle (+% Catching Away Gains)",
    "Bug7": "Worker Bee (+% Total Catching Efficiency)",
    "SoulCard1": "Forest Soul (+% Defence from Equipment)",
    "SoulCard2": "Dune Soul (+ Starting Pts in Worship)",
    "SoulCard3": "Rooted Soul (+ Starting Pts in Worship)",
    "SoulCard4": "Frigid Soul (+% Max Charge)",
    "CritterCard1": "Froge (+% Shiny Critter Chance)",
    "CritterCard2": "Crabbo (+% Trapping Efficiency)",
    "CritterCard3": "Scorpie (+% Trapping EXP)",
    "CritterCard4": "Mousey (+% Shiny Critter Chance)",
    "CritterCard5": "Owlio (+% EXP from monsters)",
    "sheep": "Sheepie (+% Defence from Equipment)",
    "flake": "Frost Flake (+ Base STR)",
    "stache": "Sir Stache (+% Card Drop Chance)",
    "bloque": "Bloque (+ Base AGI)",
    "mamoth": "Mamooth (+% Total HP)",
    "snowball": "Snowman (+% Total Damage)",
    "penguin": "Penguin (+ Base WIS)",
    "thermostat": "Thermister (+% Critical Damage)",
    "glass": "Quenchie (+ Base LUK)",
    "snakeB": "Cryosnake (+% MP regen rate)",
    "speaker": "Bop Box (+% Total Drop Rate)",
    "eye": "Neyeptune (+% Total Accuracy)",
    "ram": "Dedotated Ram (+ Weapon Power)",
    "skele": "Xylobone (+% Critical Chance)",
    "skele2": "Bloodbone (+% Total Damage)",
    "Crystal2": "Crystal Cattle (+% EXP from monsters)",
    "Starfire": "Starfire Ore (+% Mining EXP)",
    "Dreadlo": "Dreadlo Ore (+% Mining Away Gains)",
    "Godshard": "Godshard Ore (+% Forge Cap and SPD (Passive))",
    "Prehistrium": "Prehistrium Ore (+% Mining Away Gains)",
    "Tree9": "Maple Logs (+% Choppin Away Gains)",
    "Tree10": "Dandielogs (+% Choppin Speed)",
    "Tree12": "Bamboo Logs (+% Total Choppin Efficiency)",
    "Tree13": "Effervescent Logs (+% Choppin Away Gains)",
    "Tree14": "Seaweed Logs (+% Choppin Away Gains)",
    "Fish9": "Icefish (+% Fishing EXP)",
    "Fish10": "Shellfish (+% Total Fishing Efficiency)",
    "Fish11": "Jumbo Shrimp (+% Fishing Away Gains)",
    "Fish12": "Caulifish (+% Fishing Speed)",
    "Bug8": "Fairy (+% Catching Speed)",
    "Bug9": "Scarab (+% Total Catching Efficiency)",
    "Bug10": "Dust Mote (+% Catching Away Gains)",
    "Bug12": "Ladybug (+% Total Catching Efficiency)",
    "Bug13": "Firefly (+% Catching Speed)",
    "Bug14": "Fractal Fly (+% Total Catching Efficiency)",
    "CritterCard6": "Pingy (+% Shiny Critter Chance)",
    "CritterCard7": "Bunny (+% Skill AFK gain rate)",
    "CritterCard8": "Dung Beat (+% Trapping Efficiency)",
    "CritterCard9": "Honker (+% Trapping EXP)",
    "CritterCard10": "Blobfish (+% Shiny Critter Chance)",
    "CritterCard11": "Tuttle (+% Shiny Critter Chance)",
    "SoulCard5": "Squishy Soul (+% Charge Rate)",
    "SoulCard6": "Oozie Soul (+% Max Charge)",
    "SoulCard7": "Breezy Soul (+% Charge Rate)",
    "SoulCard8": "Deepsea Soul (+ Starting Pts in Worship)",
    "SpelunkingCard0": "Fearful Tunnel (+% Spelunking EXP)",
    "SpelunkingCard1": "Decaying Crevasse (+% Spelunking Efficiency)",
    "SpelunkingCard2": "Buried Church (+% Spelunking AFK Gain)",
    "SpelunkingCard3": "One Way Opening (+% Spelunking EXP)",
    "SpelunkingCard4": "Plunder Cranny (+% Spelunking AFK Gain)",
    "SpelunkingCard5": "Kelp Forest (+% Spelunking EXP)",
    "mushP": "Purp Mushroom (+% Money from Monsters)",
    "w4a2": "TV (+% Breeding EXP (Passive))",
    "w4a3": "Donut (+% Defence from Equipment)",
    "demonP": "Demon Genie (+% Crystal Mob Spawn Chance)",
    "w4b2": "Soda Can (+ Star Talent Pts (Passive))",
    "w4b1": "Flying Worm (+ Base WIS)",
    "w4b3": "Gelatinous Cuboid (+% Lab EXP gain)",
    "w4b4": "Choccie (+ Weapon Power)",
    "w4b5": "Biggole Wurm (+ Base AGI)",
    "w4c1": "Clammie (+% Multikill per tier)",
    "w4c2": "Octodar (+ Base STR)",
    "w4c3": "Flombeige (+% Critical Chance (Passive))",
    "w4c4": "Stilted Seeker (+% All Stat)",
    "Crystal3": "Crystal Custard (+px Line Width (Passive))",
    "w5a1": "Suggma (+% Multikill per tier)",
    "w5a2": "Maccie (+% Defence from Equipment)",
    "w5a3": "Mister Brightside (+% Total Drop Rate)",
    "w5a4": "Cheese Nub (+% Skill EXP (Passive))",
    "w5a5": "Stiltmole (+% Divinity EXP (Passive))",
    "w5b1": "Molti (+% Money from mobs (Passive))",
    "w5b2": "Purgatory Stalker (+ Weapon Power (Passive))",
    "w5b3": "Citringe (+% Total Damage)",
    "w5b4": "Lampar (+% EXP from monsters)",
    "w5b5": "Fire Spirit (+ Base LUK)",
    "w5b6": "Biggole Mole (+% Mining Speed)",
    "w5c1": "Crawler (+% Sailing Speed (Passive))",
    "w5c2": "Tremor Wurm (+% All Stat)",
    "caveB": "Gloomie Mushroom (+% Villager EXP (Passive))",
    "caveC": "Ancient Golem (+% Total Drop Rate (Passive))",
    "Crystal4": "Magma Geode (+% Skill Efficncy (Passive))",
    "w6a1": "Sprout Spirit (+% Total Damage)",
    "w6a2": "Ricecake (+% DEF from Equips (Passive))",
    "w6a3": "River Spirit (+% All Stat)",
    "w6a4": "Baby Troll (+% Sneaking EXP (Passive))",
    "w6a5": "Woodlin Spirit (+% Multikill per tier)",
    "w6b1": "Bamboo Spirit (+% Summoning EXP (Passive))",
    "w6b2": "Lantern Spirit (+% Farming EXP (Passive))",
    "w6b3": "Mama Troll (+% Skill AFK gain rate)",
    "w6b4": "Leek Spirit (+% Jade Coin gain (Passive))",
    "w6c1": "Ceramic Spirit (+% Cooking Spd Multi (Passive))",
    "w6c2": "Skydoggie Spirit (+ Base LUK)",
    "w6d1": "Royal Egg (+% Fighting AFK (Passive))",
    "w6d2": "Minichief Spirit (+% Total Drop Rate)",
    "w6d3": "Samurai Guardian (+% All AFK Gains(Passive))",
    "Crystal5": "Spirit Diamond (+% Sneaking Stealth (Passive))",
    "w7a1": "Equinox Broadbass (+% Spelunking Efficiency)",
    "w7a2": "Doodlefish (+% Total Damage Multi)",
    "w7a3": "Eamsy Earl (+% Class EXP Multi)",
    "w7a4": "Shellslug (+% Spelunking AFK Gain)",
    "w7a5": "Balloonfish (+% Spelunk POW (Passive))",
    "w7a6": "Noble Clam (+% Spelunking EXP)",
    "w7a7": "Litterfish (+% Spelunk Amber (Passive))",
    "w7a8": "Pufferblob (+% Class EXP Multi)",
    "w7a9": "Demonblub (+% Daily Coral (Passive))",
    "w7a10": "Spearfish (+% Stamina Regen (Passive))",
    "w7a11": "Coralcave Crab (+% Gallery Bonus (Passive))",
    "w7a12": "Coralcave Guardian (+% Drop Rate Multi)",
    "w7b1": "Trench Fish (+% Research EXP (Passive))",
    "w7b2": "Boomy Mine (+% Gaming Bit Multi (Passive))",
    "w7b3": "Pirate Underling (+% Flaggy Rate Multi (Passive))",
    "w7b4": "Eggroll (+% Research EXP (Passive))",
    "w7b5": "Jellofish (+% Farming EVO Multi (Passive))",
    "w7b6": "Kelpfish (+% Class EXP Multi)",
    "w7b7": "Mantaray (+% Drop Rate Multi)",
    "w7b8": "Glowfish (+% Research EXP (Passive))",
    "w7b9": "Ancientfish (+% Drop Rate Multi)",
    "w7b10": "Magni Pufferfin (+% Drop Rate Multi)",
    "w7b11": "Pirate Deckhand (+% Research AFK gain (Passive))",
    "w7b12": "Dreadnaught Captain (+% Drop Rate Multi)",
    "Crystal6": "Gem to W7 (+% Damage Multi (Passive))",
    "frogP": "Poisonic Frog (+ Base Dungeon MP)",
    "frogD": "Globohopper (+% Block Chance)",
    "frogY": "King Frog (+ Base Dungeon Damage)",
    "frogR": "Lava Slimer (+% Dungeon Card Chance)",
    "frogW": "Chromatium Frog (+% Dungeon Credits)",
    "frogGG": "Eldritch Croaker (% to start with RNG orb (Passive))",
    "frogGR": "Grandfrogger (% to start with RNG orb (Passive))",
    "frogGR2": "Rotting Grandfrogger (+% Dungeon Flurbos)",
    "frogGR3": "Forlorn Grandfrogger (+% Dungeon Credits)",
    "frogGR4": "Vengeful Grandfrogger (+% Dungeon Move Speed)",
    "target": "Target (+ Base Dungeon HP)",
    "rocky": "Grumblo (+% Dungeon Card Chance)",
    "steakR": "Beefie (+% Dungeon Money)",
    "totem": "Lazlo (+% RNG item rarity)",
    "cactus": "Cactopunk (+% Dungeon Boss Dmg)",
    "potatoB": "Crescent Spud (+% Dungeon MP regen)",
    "snakeZ": "Snakenhotep (+% Dungeon Drop Rate)",
    "snakeZ2": "Enraged Snakenhotep (+% Total Dungeon Dmg)",
    "snakeZ3": "Inevitable Snakenhotep (+% Dungeon Flurbos)",
    "iceknight": "Ice Guard (+% Dungeon MP regen)",
    "iceBossZ": "Glaciaxus (+% Dungeon Card Chance)",
    "iceBossZ2": "Golden Glaciaxus (+% Dungeon Credits)",
    "iceBossZ3": "Caustic Glaciaxus (+% Total Dungeon Dmg)",
    "slimeB": "Glunko The Massive (+ Weapon Power)",
    "babayaga": "Baba Yaga (+% Money from Monsters)",
    "poopBig": "Dr Defecaus (+% Total Damage)",
    "poopD": "Boop (+% Fighting AFK gain rate)",
    "wolfA": "Amarok (+% Skill AFK gain rate)",
    "wolfB": "Chaotic Amarok (+% Fighting AFK gain rate)",
    "wolfC": "Radiant Amarok (+ Weapon Power)",
    "babaHour": "Biggie Hours (+% Double AFK claim chance)",
    "babaMummy": "King Doot (+% Total Drop Rate)",
    "Boss2A": "Efaunt (+% EXP from monsters)",
    "Boss2B": "Chaotic Efaunt (+% Skill EXP)",
    "Boss2C": "Gilded Efaunt (+ Star Talent Pts (Passive))",
    "mini3a": "Dilapidated Slush (+% Money from Monsters)",
    "Boss3A": "Chizoar (+% Cog Build Spd (Passive))",
    "Boss3B": "Chaotic Chizoar (+% Shrine Effects (Passive))",
    "Boss3C": "Blighted Chizoar (+% All Stat)",
    "mini4a": "Mutated Mush (+% Cooking EXP gain)",
    "Boss4A": "Massive Troll (+% Kitchen Speed (Passive))",
    "Boss4B": "Chaotic Troll (+% All Skill Efficiency)",
    "Boss4C": "Blitzkrieg Troll (+% Total Damage)",
    "mini5a": "Domeo Magmus (+% Total Drop Rate (Passive))",
    "Boss5A": "Kattlekruk (+% Sailing Speed (Passive))",
    "Boss5B": "Chaotic Kattlekruk (+% EXP from monsters)",
    "Boss5C": "Sacrilegious Kattlekruk (+% Money from Monsters)",
    "mini6a": "Demented Spiritlord (+% Fighting AFK gain rate)",
    "Boss6A": "Emperor (+% Total Drop Rate)",
    "Boss6B": "Chaotic Emperor (+% Total Damage Multi)",
    "Boss6C": "Sovereign Emperor (+% Multikill per tier)",
    "ghost": "Ghost (Event) (+% Monster EXP While Active)",
    "xmasEvent": "Giftmas Blobulyte (+% Total Drop Rate)",
    "xmasEvent2": "Meaning of Giftmas (+% Money from Monsters)",
    "slimeR": "Valenslime (+% Defence from Equipment)",
    "loveEvent": "Loveulyte (+% Total HP)",
    "loveEvent2": "Chocco Box (+% Boost Food Effect)",
    "loveEvent3": "Giant Rose (+% EXP from monsters)",
    "sheepB": "Floofie (+% MP regen rate)",
    "snakeY": "Shell Snake (+ Base LUK)",
    "EasterEvent1": "Egggulyte (+% Card Drop Chance)",
    "EasterEvent2": "Egg Capsule (+% Critical Damage)",
    "shovelY": "Plasti Doug (+ Base Defence)",
    "crabcakeB": "Mr Blueberry (+% Total Drop Rate)",
    "SummerEvent1": "Coastiolyte (+% Fishing Away Gains)",
    "SummerEvent2": "Summer Spirit (+% Catching EXP)",
    "xmasEvent3": "Golden Giftmas Box (+% Defence from Equipment)",
    "springEvent1": "Bubbulyte (+% Class EXP (Passive))",
    "springEvent2": "Spring Splendor (+% All Skill EXP (Passive))",
    "fallEvent1": "Falloween Pumpkin (+ Star Talent Pts (Passive))",
    "anni4Event1": "IdleOn 4th Anniversary (+% Drop Rate (Passive))",
    "cropfallEvent1": "Bort The Cornhusk (+% Gold Food Effect (Passive))",
    "xmasEvent4": "Big Ol Giftmas Box (+% Catching Away Gains)",
    "luckEvent1": "Luckulyte (+% Drop Rate (Passive))",
    "luckEvent2": "Potluck (+% Money from Monsters)",
    "anni5Event1": "IdleOn 5th Anniversary (+% Gold Food Effect (Passive))"
};

export { cardEquipMap };
